#!/bin/sh

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:lib
./server
#./demo "CREATE TABLE fit_hai (id INT, first_name VARCHAR(7), last_name VARCHAR(8));"
#./demo "CREATE TABLE studentss (id INT, first_name VARCHAR(7), last_name VARCHAR(8));"
#./demo "CREATE TABLE test (id INT, first_name VARCHAR(7), last_name VARCHAR(8));"
#./client ".tables"
#./client ".tables"
#./client ".tables"
#./client ".tables"
#./client ".tables"
#./client ".tables"
#./demo ".schema studentss"
#./demo ".schema test"
#./demo "DROP TABLE fit_hai;"
#./demo "INSERT INTO studentss VALUES (45, 'Oscar', 'Svensson');"
#./demo "INSERT INTO studentss VALUES (46, 'Oscar', 'Svensson');"
#./demo "INSERT INTO studentss VALUES (47, 'Oscar', 'Svensson');"
#./demo "INSERT INTO test VALUES (1, 'Fabia', 'Afzal');"
#./demo "INSERT INTO test VALUES (2, 'Sam', 'John');"
#./demo "INSERT INTO test VALUES (3, 'Sam', 'John');"
#./demo "INSERT INTO fit_hai VALUES (48, 'Oscar', 'Svensson');"
#./demo "SELECT * FROM studentss;"
#./demo "SELECT * FROM test;"
#./demo "CREATE TABLE studentss (id INT, first_name VARCHAR(7), last_name VARCHAR(8), PRIMARY KEY(id));"
#/demo "SELECT first_name, last_name FROM studentss;"
#./demo "DELETE FROM studentss WHERE id=47;"
#./demo "DELETE FROM test WHERE id=3;"
#./demo "UPDATE studentss SET first_name='Emil', last_name='Johansson' WHERE id=46;"
#./demo "UPDATE test SET first_name='FABIA', last_name='AFZAL' WHERE id=1;"
